### ISSUE TITLE
Возможные коллизии

### ISSUE THREAD

**Issue by vporoshok** [vladimirbulichev/gotest#1]
Здравствуйте! Есть несколько замечаний по коду, не могли бы вы их исправить или описать как это можно сделать.
1. Цикл на строках 48:50 достаточно ресурсоёмкий, можно ли как-то его оптимизировать?
2. Переменная `total` изменяется из нескольких горутин и в ней могут быть коллизии записи. К чему это может привести и как это исправить?

**Comment by vladimirbulichev** [comment]
> Здравствуйте! Есть несколько замечаний по коду, не могли бы вы их исправить или описать как это можно сделать.
> 
> 1. Цикл на строках 48:50 достаточно ресурсоёмкий, можно ли как-то его оптимизировать?
> 2. Переменная `total` изменяется из нескольких горутин и в ней могут быть коллизии записи. К чему это может привести и как это исправить?

2. судя по всему к ошибке времени выполнения конкурентного доступа к одной области памяти (но это лишь предположение, основанное на описании из ошибок которые описаны в туториале:)). Исправил внесением тотала в класс watchdog тк там реализованы блокировки  (с небольшим нарушением принципа единственности отвественности :) )

по п1 еще буду думать

**Comment by vladimirbulichev** [comment]
п1) изменил бесконечный цикл на ожидание канала
